-- 客户表
CREATE TABLE T_CUSTOMER (
  ID      TEXT NOT NULL PRIMARY KEY,
  NAME    TEXT NOT NULL,
  ADDRESS TEXT,
  PHONE   TEXT NOT NULL,
  DELETED INTEGER
);

-- 车辆信息表
CREATE TABLE T_VEHICLE (
  ID          TEXT NOT NULL PRIMARY KEY,  --主键
  CUSTOMER_ID TEXT NOT NULL,  --客户ID
  PRODUCT     TEXT,           --产品名称
  PERIOD      TEXT,           --期次
  MODEL       TEXT            --车辆类型
);