-- 客户表
CREATE TABLE T_CUSTOMER (
  ID      KEY NOT NULL PRIMARY KEY,
  NAME    TEXT NOT NULL,
  ADDRESS TEXT,
  PHONE   TEXT NOT NULL,
  DELETED INTEGER
);

-- 车辆信息表
CREATE TABLE T_VEHICLE (
  ID      KEY NOT NULL PRIMARY KEY,
  CUSTOMER_ID TEXT NOT NULL,
  PRODUCT TEXT,
  NAME    TEXT NOT NULL,
  ADDRESS TEXT,
  PHONE   TEXT NOT NULL,
  DELETED INTEGER
);